FROM curlimages/curl:8.11.0 AS jars
RUN curl -fsSL -o /tmp/postgresql.jar \
    https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.3/postgresql-42.7.3.jar

FROM apache/hive:3.1.3
COPY --from=jars /tmp/postgresql.jar /opt/hive/lib/postgres.jar
COPY hive-metastore/hive-site.xml.template /opt/hive-custom-conf-template/hive-site.xml
COPY hive-metastore/entrypoint-wrapper.sh /entrypoint-wrapper.sh

USER root
RUN chmod +x /entrypoint-wrapper.sh

ENTRYPOINT ["/entrypoint-wrapper.sh"]
